### ISSUE TITLE
Change the color of the horizontal lines

### ISSUE THREAD

**Issue by TanZng** [SaswatPadhi/pseudocode.js#22]
While displaying the caption of an algorithm, using `algorithm ` environment as a 'float' wrapper with a with black background it's unable to see the lines.

![image](https://user-images.githubusercontent.com/25267490/82594087-2bfb9200-9b69-11ea-84e0-40b05b297530.png)

**Comment by SaswatPadhi** [comment]
Sorry about the late response. The past month has been extremely busy.

You can change the colors by modifying the border colors. Add this CSS snippet somewhere in your document:

```css
.ps-algorithm {
  border-top: 2px solid white !important;
  border-bottom: 2px solid white !important;
}

.ps-algorithm.with-caption > .ps-line {
  border-bottom: 2px solid white !important;
}
```

Here is a live example: https://jsfiddle.net/orxy83jk/8/

![Screenshot_2020-06-05 Edit fiddle - JSFiddle - Code Playground](https://user-images.githubusercontent.com/1577944/83830555-fe6c2800-a6d4-11ea-9499-71c801a4b8bb.png)

Let me know if you face any issues.
